# Generated by Django 2.1.7 on 2019-04-04 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('fullname_kr', models.CharField(blank=True, max_length=120, null=True)),
                ('fullname_en', models.CharField(blank=True, max_length=120, null=True)),
                ('keywords', models.TextField(default='')),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('history', models.TextField(blank=True, default='', null=True)),
                ('logo', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optname', models.CharField(default='init', max_length=120)),
                ('idwords', models.TextField(default='[{"럭셔리": "럭셔리 고급 호화 과시 명품 luxury 비싼 고가 expensive pricy pricey", "캐주얼": "캐주얼 캐쥬얼 casual 스타일리시 스타일리쉬 stylish"}, {"유니크": "유니크 독특 독창 unique 개성 only 참신 신선 특이 아이디어 철학", "대중성": "대중 popular 널리 흔한 massive mass 대중성"}, {"정통성": "정통 클래식 classic 품격 약속 신뢰 믿음 예측 견고 품질 안정", "트렌디": "트렌디 트랜디 트렌드 트랜드 유행 trend trendy 변화 새로운 민감 예민 신상 최신"}, {"포멀": "포멀 formal 노멀 normal 평범 일상 무난 기본 베이스 베이직 base basic", "액티브": "화제 인기 hot 튀는 액티브 active 앞서가는 실험 과감 선도 선구 대담"}]')),
                ('api', models.CharField(default='http://127.0.0.1:8080/api', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worldcup', models.TextField(blank=True, default='{}', null=True)),
                ('likes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
