# Generated by Django 2.1.5 on 2019-02-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='price',
        ),
    ]
