# Generated by Django 2.1.5 on 2019-04-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Environ',
            new_name='Option',
        ),
    ]
