# Generated by Django 2.1.5 on 2019-04-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cluster',
        ),
    ]
