# Generated by Django 2.1.5 on 2019-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190320_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rates',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
