# Generated by Django 2.1.5 on 2019-04-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190403_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='idwords',
            field=models.TextField(default='[{"\\ub7ed\\uc154\\ub9ac": "\\ub7ed\\uc154\\ub9ac \\uace0\\uae09 \\ud638\\ud654 \\uacfc\\uc2dc \\uba85\\ud488 luxury \\ube44\\uc2fc \\uace0\\uac00 expensive pricy pricey", "\\uce90\\uc8fc\\uc5bc": "\\uce90\\uc8fc\\uc5bc \\uce90\\uc96c\\uc5bc casual \\uc2a4\\ud0c0\\uc77c\\ub9ac\\uc2dc \\uc2a4\\ud0c0\\uc77c\\ub9ac\\uc26c stylish"}, {"\\uc720\\ub2c8\\ud06c": "\\uc720\\ub2c8\\ud06c \\ub3c5\\ud2b9 \\ub3c5\\ucc3d unique \\uac1c\\uc131 only \\ucc38\\uc2e0 \\uc2e0\\uc120 \\ud2b9\\uc774 \\uc544\\uc774\\ub514\\uc5b4 \\ucca0\\ud559", "\\ub300\\uc911\\uc131": "\\ub300\\uc911 popular \\ub110\\ub9ac \\ud754\\ud55c massive mass \\ub300\\uc911\\uc131"}, {"\\uc815\\ud1b5\\uc131": "\\uc815\\ud1b5 \\ud074\\ub798\\uc2dd classic \\ud488\\uaca9 \\uc57d\\uc18d \\uc2e0\\ub8b0 \\ubbff\\uc74c \\uc608\\uce21 \\uacac\\uace0 \\ud488\\uc9c8 \\uc548\\uc815", "\\ud2b8\\ub80c\\ub514": "\\ud2b8\\ub80c\\ub514 \\ud2b8\\ub79c\\ub514 \\ud2b8\\ub80c\\ub4dc \\ud2b8\\ub79c\\ub4dc \\uc720\\ud589 trend trendy \\ubcc0\\ud654 \\uc0c8\\ub85c\\uc6b4 \\ubbfc\\uac10 \\uc608\\ubbfc \\uc2e0\\uc0c1 \\ucd5c\\uc2e0"}, {"\\ud3ec\\uba40": "\\ud3ec\\uba40 formal \\ub178\\uba40 normal \\ud3c9\\ubc94 \\uc77c\\uc0c1 \\ubb34\\ub09c \\uae30\\ubcf8 \\ubca0\\uc774\\uc2a4 \\ubca0\\uc774\\uc9c1 base basic", "\\uc561\\ud2f0\\ube0c": "\\ud654\\uc81c \\uc778\\uae30 hot \\ud280\\ub294 \\uc561\\ud2f0\\ube0c active \\uc55e\\uc11c\\uac00\\ub294 \\uc2e4\\ud5d8 \\uacfc\\uac10 \\uc120\\ub3c4 \\uc120\\uad6c \\ub300\\ub2f4"}]'),
        ),
    ]
