# Generated by Django 2.1.5 on 2019-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='idwords',
            field=models.TextField(default=''),
        ),
    ]
