# Generated by Django 2.1.5 on 2019-03-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190320_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rates',
            new_name='worldcup',
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
