# Generated by Django 2.1.5 on 2019-04-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filtered_image',
            field=models.ImageField(upload_to='test'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='test'),
        ),
    ]
