# Generated by Django 2.1.5 on 2019-02-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_brand_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cluster',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
