# Generated by Django 2.1.7 on 2019-04-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190402_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Settings',
        ),
    ]
