# Generated by Django 2.1.5 on 2019-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190425_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='filtered_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/%Y/%m/%d/origin'),
        ),
    ]
