# Generated by Django 2.1.5 on 2019-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_brand_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='wordcloud',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
