# Generated by Django 2.1.5 on 2019-04-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190403_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='identity',
        ),
    ]
