# Generated by Django 2.1.7 on 2019-04-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190402_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Options',
        ),
    ]
