# Generated by Django 2.1.5 on 2019-04-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='awareness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
