# Generated by Django 2.1.7 on 2019-04-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190402_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idwords', models.TextField(default='1234')),
            ],
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
