# Generated by Django 2.1.5 on 2019-03-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_brand_wordcloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='wordfreq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
