# Generated by Django 2.1.7 on 2019-04-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190402_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='optname',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='option',
            name='idwords',
            field=models.TextField(default=''),
        ),
    ]
