# Generated by Django 2.1.7 on 2019-03-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_brand_wordfreq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='wordcloud',
        ),
    ]
