# Generated by Django 2.1.5 on 2019-05-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190502_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='awareness',
        ),
    ]
