# Generated by Django 2.1.7 on 2019-04-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190402_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='api',
            field=models.CharField(default='http://127.0.0.1:8080/api', max_length=120),
        ),
    ]
