# Generated by Django 2.1.5 on 2019-03-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190310_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='fullname_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='fullname_kr',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
