# Generated by Django 2.1.7 on 2019-05-27 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_commentpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='fan',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='love',
            field=models.ManyToManyField(blank=True, to='app.Brand'),
        ),
    ]
