# Generated by Django 2.1.7 on 2019-05-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190527_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='love',
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(blank=True, default='', to='app.Brand'),
        ),
    ]
