# Generated by Django 2.1.5 on 2019-03-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='history',
            field=models.TextField(default=''),
        ),
    ]
