# Generated by Django 2.1.5 on 2019-05-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190527_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.AddField(
            model_name='profile',
            name='brand_likes',
            field=models.ManyToManyField(blank=True, to='app.Brand'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_likes',
            field=models.ManyToManyField(blank=True, to='app.Post'),
        ),
    ]
