# Generated by Django 2.1.5 on 2019-05-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190530_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myfavorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myfavorite_set', to='app.Brand'),
        ),
    ]
