# Generated by Django 2.1.7 on 2019-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_brand_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='wordfreq',
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='history',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='identity',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
