# Generated by Django 2.1.5 on 2019-03-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_brand_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
