# Generated by Django 2.1.5 on 2019-03-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190315_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='score',
        ),
    ]
