# Generated by Django 2.1.7 on 2019-06-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190616_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtags',
            new_name='brands_related',
        ),
    ]
