# Generated by Django 2.1.7 on 2019-06-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='author',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='membership',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
