# Generated by Django 2.2.2 on 2019-07-03 13:32

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nlikes', models.IntegerField(default='0')),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('feed_image', models.ImageField(upload_to=app.models.feed_image_path)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Profile')),
                ('hashtags', models.ManyToManyField(blank=True, to='app.Hashtag')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Brand')),
            ],
        ),
    ]
